### ISSUE TITLE
Units are solid to others on their side

### ISSUE THREAD

**Issue by james7132** [SmugilouGazilou/touhouemblem#20]
### Expected Behavior:
Units on the player's or enemy's side do not occlude the movement range of units on their side, but are solid to their opponents. Player units should block the advance of Enemy units, and vice versa.

### Current Behavior:
Every unit is solid and occludes movement to every other unit.

**Comment by SmugilouGazilou** [comment]
This is already coming forth for the upcoming update. All I can think of beyond that, is making it a toggle-type thing since some people might not want that on.
