### ISSUE TITLE
Credit artists whose art is being used as a part of the game

### ISSUE THREAD

**Issue by james7132** [SmugilouGazilou/touhouemblem#21]
I've noticed that all of the characters have art pulled from artists who have not given consent to have their art used in the game, but see no attribution to their work.

Please credit these artists properly, or substitute it with your own art and cease distribution of older versions using said art.

**Comment by SmugilouGazilou** [comment]
Probably. As non-serious as this game may be, that'd be a generally good idea. I already know who to credit so shouldn't be a problem.

Probably add a text document or something to come with the game. Albeit making my own art wouldn't be so hard either. But lest I stop using their art, I'll give them credits for the time being.
