### ISSUE TITLE
Post releases using Github Releases

### ISSUE THREAD

**Issue by james7132** [SmugilouGazilou/touhouemblem#22]
There's a Releases tab where one can upload WIP/completed releases. I strongly advise using this if you are already using Github for management and change logging.

**Comment by SmugilouGazilou** [comment]
Didn't even notice that. Oh dear. That'll help a lot. Maybe. Main reason I decided to use Github was to better organize myself, for the most part.

Not many people dwaddle around here, but I'll use it alongside any other forms of releases.
